export const suggestions = [
  "Milk 🥛", 
  "Eggs 🥚", 
  "Cheese 🧀", 
  "Yogurt 🥣", 
  "Butter 🧈", 
  "Apples 🍎", 
  "Bananas 🍌", 
  "Oranges 🍊", 
  "Grapes 🍇", 
  "Mangoes 🥭", 
  "Tomatoes 🍅", 
  "Potatoes 🥔", 
  "Onions 🧅", 
  "Carrots 🥕", 
  "Cabbage 🥬", 
  "Spinach 🥗", 
  "Broccoli 🥦", 
  "Garlic 🧄", 
  "Ginger 🫚", 
  "Cauliflower 🥦", 
  "Bread 🍞", 
  "Buns 🍔", 
  "Croissant 🥐", 
  "Rice 🍚", 
  "Wheat Flour 🌾", 
  "Oats 🥣", 
  "Pasta 🍝", 
  "Noodles 🍜", 
  "Cooking Oil 🛢️", 
  "Salt 🧂", 
  "Sugar 🍬", 
  "Tea 🍵", 
  "Coffee ☕", 
  "Juice 🧃", 
  "Coke 🥤", 
  "Biscuits 🍪", 
  "Chips 🍟", 
  "Popcorn 🍿", 
  "Toothpaste 🪥", 
  "Shampoo 🧴", 
  "Soap 🧼", 
  "Toilet Paper 🧻", 
  "Dish Soap 🧽", 
  "Detergent 🧺", 
  "Green Beans 🫘", 
  "Beetroot 🥬", 
  "Peas 🟩", 
  "Cucumber 🥒", 
  "Zucchini 🥒", 
  "Papaya 🍈", 
  "Pineapple 🍍", 
  "Avocado 🥑", 
  "Strawberries 🍓", 
  "Blueberries 🫐", 
  "Kiwi 🥝", 
  "Lemons 🍋", 
  "Limes 🍈", 
  "Brinjal 🍆", 
  "Okra 🥒", 
  "Pumpkin 🎃", 
  "Radish 🥗", 
  "Corn 🌽", 
  "Celery 🥬", 
  "Lettuce 🥬", 
  "Mushrooms 🍄", 
  "Paneer 🧀", 
  "Tofu 🥢", 
  "Chicken 🍗", 
  "Eggplant 🍆", 
  "Green Chilli 🌶️", 
  "Red Chilli 🌶️", 
  "Ketchup 🍅", 
  "Mayonnaise 🥪", 
  "Pickles 🥒", 
  "Honey 🍯", 
  "Jam 🍓", 
  "Mustard 🌭", 
  "Vinegar 🍶", 
  "Soy Sauce 🥢", 
  "Black Pepper 🌶️", 
  "Cumin 🌿", 
  "Turmeric 🟡", 
  "Coriander 🌿", 
  "Cinnamon 🌰", 
  "Bay Leaf 🍃", 
  "Chilli Powder 🌶️", 
  "Cardamom 🟢", 
  "Nutmeg 🌰", 
  "Baking Powder 🥄", 
  "Baking Soda 🥄", 
  "All-Purpose Flour 🌾", 
  "Coconut 🥥", 
  "Dry Fruits 🥜", 
  "Raisins 🍇", 
  "Almonds 🥜", 
  "Cashews 🥜", 
  "Toothbrush 🪥", 
  "Face Wash 🧴", 
  "Handwash 🧴", 
  "Shaving Cream 🪒", 
  "Sanitizer 🧴"
];
