export const suggestions = [
  "Achappam 🍪",
  "Almonds 🥜",
  "Avocado 🥑",
  "Bakery Items 🍞",
  "Baking Powder 🥄",
  "Baking Soda 🥄",
  "Beetroot 🥬",
  "Biscuits 🍪",
  "Black Pepper 🌶️",
  "Blueberries 🫐",
  "Bread 🍞",
  "Brinjal 🍆",
  "Cabbage 🥬",
  "Cake 🍰",
  "Cardamom 🟢",
  "Cashews 🥜",
  "Coconut 🥥",
  "Coffee ☕",
  "Corn 🌽",
  "Coriander 🌿",
  "Cucumber 🥒",
  "Cumin 🌿",
  "Detergent 🧺",
  "Dish Soap 🧽",
  "Eggs 🥚",
  "Eggplant 🍆",
  "Face Wash 🧴",
  "Fish 🐟",
  "Garlic 🧄",
  "Ginger 🫚",
  "Grapes 🍇",
  "Green Beans 🫘",
  "Green Chilli 🌶️",
  "Honey 🍯",
  "Jam 🍓",
  "Karivepp 🍃",
  "Ketchup 🍅",
  "Kiwi 🥝",
  "Lettuce 🥬",
  "Lemons 🍋",
  "Limes 🍈",
  "Mandhi masala 🍛",
  "Maggie cube 🍜",
  "Mangoes 🥭",
  "Match Box 🧯",
  "Milk 🥛",
  "Mushrooms 🍄",
  "Mustard 🌭",
  "Noodles 🍜",
  "Nutmeg 🌰",
  "Okra 🥒",
  "Onions 🧅",
  "Papaya 🍈",
  "Peas 🟩",
  "Pickles 🥒",
  "Paneer 🧀",
  "Pasta 🍝",
  "Pineapple 🍍",
  "Potatoes 🥔",
  "Pumpkin 🎃",
  "Putt podi 🍚",
  "Radish 🥗",
  "Raisins 🍇",
  "Rice 🍚",
  "Red Chilli 🌶️",
  "Salt 🧂",
  "Sanitizer 🧴",
  "Shampoo 🧴",
  "Shaving Cream 🪒",
  "Soap 🧼",
  "Soy Sauce 🥢",
  "Spinach 🥗",
  "Sugar 🍬",
  "Tea 🍵",
  "Toilet Paper 🧻",
  "Tomatoes 🍅",
  "Toothbrush 🪥",
  "Toothpaste 🪥",
  "Turmeric 🟡",
  "Vinegar 🍶",
  "Watermelon 🍉",
  "Wheat Flour 🌾",
  "Zucchini 🥒"
];
